apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: viajesgvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: gianellovr/viajesgvr-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: viajesgvr-common-config
          env:
            - name: DB_URL
              value: "jdbc:mysql:///=true&useSSL=false&serverTimezone=UTC"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: viajesgvr
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8080
      targetPort: 8080