apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: viajesgvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: gianellovr/viajesgvr-reservation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: viajesgvr-common-config
          env:
            - name: SPRING_APPLICATION_NAME
              value: "reservation-service"
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3306/db_viajesgvr_reservation?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/db_viajesgvr_reservation?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: DB_PASSWORD
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "reservation-service"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "reservation-service:8080"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: viajesgvr
spec:
  type: ClusterIP
  selector:
    app: reservation-service
  ports:
    - port: 8080
      targetPort: 8080