apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: viajesgvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gianellovr/viajesgvr-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: frontend-tls
              mountPath: /etc/nginx/tls
              readOnly: true
      volumes:
        - name: frontend-tls
          secret:
            secretName: frontend-tls
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: viajesgvr
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443