apiVersion: v1
kind: ConfigMap
metadata:
  name: viajesgvr-common-config
  namespace: viajesgvr
data:
  SERVER_PORT: "8080"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"