apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: viajesgvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: gianellovr/viajesgvr-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: viajesgvr-common-config
          env:
            - name: SPRING_APPLICATION_NAME
              value: api-gateway
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: api-gateway:8080
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: viajesgvr
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080