apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-status-mysql
  namespace: viajesgvr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-status-mysql
  template:
    metadata:
      labels:
        app: reservation-status-mysql
    spec:
      containers:
        - name: reservation-status-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viajesgvr-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: db_viajesgvr_reservation_status
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-status-mysql
  namespace: viajesgvr
spec:
  type: ClusterIP
  selector:
    app: reservation-status-mysql
  ports:
    - port: 3306
      targetPort: 3306